name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize] # the workflow will run when a PR into the main branch is opened or updated

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
      - name: build
        id: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@f5bea478b80a774068179089247f13d60abc5010
        with:
          start: npm run start-prod
          command: npm run test:e2e
          wait-on: http://localhost:5000
      - name: deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')  }}
        uses: akhileshns/heroku-deploy@v79ef2ae4ff9b897010907016b268fd0f88561820 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokedex-97 # Must be unique in Heroku
          heroku_email: babyzewdie@gmail.com
          healthcheck: 'https://pokedex-97.herokuapp.com/health'
          checkstring: 'ok'
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: The job has failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: commit made by ${{ github.event.head_commit.committer.name }} failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ github.repository.owner.avatar_url }}
          text: Job Failed
  tag_release:
    needs: [simple_deployment_pipeline] #depends on the first job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@ce4b5ffa38e072fa7a901e417253c438fcc2ccce
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          WITH_V: true
      - name: The job has succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          text: A new version of Pokedex deployed.
          details: to 'https://pokedex-97.herokuapp.com/' by ${{ github.event.head_commit.committer.name }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ github.repository.owner.avatar_url }}
